<?php

namespace {

    use SilverStripe\AssetAdmin\Forms\UploadField;
    use SilverStripe\Assets\Image;
    use SilverStripe\CMS\Model\SiteTree;

    class Page extends SiteTree
    {
        private static $db = [];

        private static $has_one = [
            'Picture' => Image::class
        ];

        private static $has_many = [
            'Pictures' => Image::class
        ];

        public function getCMSFields()
        {
            $fields =  parent::getCMSFields(); // TODO: Change the autogenerated stub

            $fields->addFieldToTab('Root.Images', UploadField::create('Picture'));
            $fields->addFieldToTab('Root.Images', UploadField::create('Pictures'));

            return $fields;
        }
    }
}
